# File: .github/workflows/OIDC_workflow.yml

name: Run Terraform with OIDC
on:
  push:
    branches:
      - "release/**"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        shell: bash
        run: echo "::set-output name=value::${GITHUB_REF#refs/heads/}"
        id: get_branch

      - name: Checkout
        uses: actions/checkout@v3

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: entrypoint/${{ steps.get_branch.outputs.value }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: entrypoint/${{ steps.get_branch.outputs.value }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: entrypoint/${{ steps.get_branch.outputs.value }}
