# File: .github/workflows/OIDC_workflow.yml

name: Run Terraform with OIDC
on:
  push:
    branches:
      - "release/**"

permissions:
  id-token: write
  contents: read

# defaults:
#   run:
#     working-directory: entrypoint/functions-java

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: debug
        id: debug
        run: tree

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
